/**
 * TypeScript mirror of backend/app/services/scoring_service.py.
 * Used for instant, offline recomputation (captured signals, simulator).
 * Parity with Python is enforced by src/services/scoring.test.ts against
 * data/demo/scoring_fixture.json (generated by backend/tests/make_fixtures.py).
 */
import {
  CATEGORIES,
  type ByCategory,
  type Category,
  type District,
  type IndicatorStat,
  type ModelSpec,
} from '../types/data'

export function deficit(raw: number | null | undefined, stat: IndicatorStat | undefined): number | null {
  if (raw === null || raw === undefined || !stat) return null
  const span = stat.max - stat.min
  if (span <= 0) return 0
  let x = (raw - stat.min) / span
  if (stat.direction === 'lower_worse') x = 1 - x
  return Math.max(0, Math.min(100, x * 100))
}

export function weightedMean(pairs: Array<[number | null | undefined, number]>): number | null {
  let num = 0
  let den = 0
  for (const [v, w] of pairs) {
    if (v === null || v === undefined || w <= 0) continue
    num += v * w
    den += w
  }
  return den === 0 ? null : num / den
}

export function categoryNeeds(
  raw: Record<string, number | null>,
  model: ModelSpec,
  stats: Record<string, IndicatorStat>,
): ByCategory<number | null> {
  const out = {} as ByCategory<number | null>
  for (const cat of CATEGORIES) {
    const defs = model.indicators.filter((d) => d.category === cat)
    out[cat] = weightedMean(defs.map((d) => [deficit(raw[d.key], stats[d.key]), d.weight]))
  }
  return out
}

export function composeNeed(catNeed: number | null, vul: number | null, exp: number | null, model: ModelSpec): number | null {
  if (catNeed === null) return null
  const w = model.composite_weights
  return weightedMean([
    [catNeed, w.category_need],
    [vul, w.vulnerability],
    [exp, w.exposure],
  ])
}

export function overallCategoryNeed(cn: ByCategory<number | null>, model: ModelSpec): number | null {
  return weightedMean(CATEGORIES.map((c) => [cn[c], model.category_weights[c] ?? 1]))
}

function bisectLeft(a: number[], x: number): number {
  let lo = 0
  let hi = a.length
  while (lo < hi) {
    const mid = (lo + hi) >> 1
    if (a[mid] < x) lo = mid + 1
    else hi = mid
  }
  return lo
}

function bisectRight(a: number[], x: number): number {
  let lo = 0
  let hi = a.length
  while (lo < hi) {
    const mid = (lo + hi) >> 1
    if (x < a[mid]) hi = mid
    else lo = mid + 1
  }
  return lo
}

/** Mid-rank percentile, 0..100, tie-aware (same as Python). */
export function percentileRanks(values: Array<number | null>): Array<number | null> {
  const present = values.filter((v): v is number => v !== null).sort((a, b) => a - b)
  const n = present.length
  return values.map((v) => {
    if (v === null || n === 0) return null
    const below = bisectLeft(present, v)
    const equal = bisectRight(present, v) - below
    return (100 * (below + 0.5 * equal)) / n
  })
}

export function unheard(need: number | null, demand: number | null): number | null {
  if (need === null || demand === null) return null
  return need * (1 - demand / 100)
}

export function signalRate(count: number, population: number | null): number | null {
  if (!population || population <= 0) return null
  return (count / population) * 100_000
}

/**
 * Recompute demand + unheard for scored districts given per-district signal
 * counts (synthetic baseline + captured). Returns new objects; input untouched.
 */
export function applyDemand(scored: District[], extra: Record<string, Partial<ByCategory<number>>> = {}): District[] {
  const rows = scored.map((d) => {
    const add = extra[d.id] ?? {}
    const signals = { ...d.signals }
    for (const c of CATEGORIES) signals[c] = (signals[c] ?? 0) + (add[c] ?? 0)
    return {
      ...d,
      signals,
      captured: add,
      signal_rate: { ...(d.signal_rate ?? {}) } as ByCategory<number | null>,
      demand_by_category: { ...(d.demand_by_category ?? {}) } as ByCategory<number | null>,
      unheard_by_category: { ...(d.unheard_by_category ?? {}) } as ByCategory<number | null>,
    }
  })
  for (const cat of CATEGORIES) {
    const rates = rows.map((d) => signalRate(d.signals[cat] ?? 0, d.population_for_rates))
    const ranks = percentileRanks(rates)
    rows.forEach((d, i) => {
      d.signal_rate![cat] = rates[i]
      d.demand_by_category![cat] = ranks[i]
      d.unheard_by_category![cat] = unheard(d.need_by_category?.[cat] ?? null, ranks[i])
    })
  }
  const totals = rows.map((d) => signalRate(CATEGORIES.reduce((s, c) => s + (d.signals[c] ?? 0), 0), d.population_for_rates))
  const ranks = percentileRanks(totals)
  rows.forEach((d, i) => {
    d.signal_rate_total = totals[i]
    d.demand_score = ranks[i]
    d.unheard_index = unheard(d.need_score, ranks[i])
  })
  const order = [...rows].sort((a, b) => (b.unheard_index ?? -1) - (a.unheard_index ?? -1) || (a.id < b.id ? -1 : 1))
  order.forEach((d, i) => (d.unheard_rank = i + 1))
  return rows
}

export function metricFor(d: District, mode: 'need' | 'demand' | 'unheard', category: Category | 'all'): number | null {
  if (d.data_status !== 'scored') return null
  if (category === 'all') return mode === 'need' ? d.need_score : mode === 'demand' ? d.demand_score : d.unheard_index
  const field = mode === 'need' ? d.need_by_category : mode === 'demand' ? d.demand_by_category : d.unheard_by_category
  return field?.[category] ?? null
}

export const r1 = (x: number | null | undefined): string => (x === null || x === undefined ? '—' : (Math.round(x * 10) / 10).toFixed(1))
export const fmtInt = (x: number | null | undefined): string => (x === null || x === undefined ? '—' : Math.round(x).toLocaleString('en-IN'))

export type { Category }
