import type { ReactNode } from 'react'
import { ApiError } from '../services/api'

export function explainError(e: unknown): { title: string; message: string } {
  if (e instanceof ApiError) {
    const titles: Record<string, string> = {
      gemini_not_configured: 'Gemini not configured',
      gemini_auth: 'Gemini key rejected',
      gemini_timeout: 'Gemini timed out',
      gemini_rate_limited: 'Gemini rate-limited',
      gemini_malformed: 'Gemini output rejected',
      gemini_unreachable: 'Gemini unreachable',
      gemini_server_error: 'Gemini service error',
      gemini_model_not_found: 'Gemini model unavailable',
      backend_unreachable: 'Analysis engine offline',
      timeout: 'Analysis engine timed out',
      simulation_unavailable: 'Simulation unavailable',
      insufficient_data: 'Insufficient data',
    }
    return { title: titles[e.code] ?? 'Request failed', message: e.message }
  }
  return { title: 'Something went wrong', message: e instanceof Error ? e.message : String(e) }
}

export function ErrorState({ error, onRetry, compact }: { error: unknown; onRetry?: () => void; compact?: boolean }) {
  const { title, message } = explainError(error)
  return (
    <div className={'state state--error' + (compact ? ' state--compact' : '')} role="alert">
      <p className="state__title">UNAVAILABLE — {title}</p>
      <p className="state__msg">{message}</p>
      <p className="state__msg">No AI output is shown in its place. Deterministic scores are unaffected.</p>
      {onRetry && (
        <button type="button" className="btn btn--ghost btn--sm" onClick={onRetry}>
          Retry
        </button>
      )}
    </div>
  )
}

export function Loading({ label }: { label: string }) {
  return (
    <div className="state state--loading" role="status" aria-live="polite">
      <span className="skeleton" aria-hidden="true" />
      <span className="skeleton skeleton--short" aria-hidden="true" />
      <span className="state__msg">{label}</span>
    </div>
  )
}

export function AiBadge({ model, cached, via }: { model: string | null; cached?: boolean; via?: string }) {
  return (
    <span className="badge badge--ai" title="Generated by Google Gemini through the UNHEARD backend; schema-validated and grounding-checked.">
      {via ?? 'Gemini'}
      {model ? ` · ${model}` : ''}
      {cached ? ' · cached' : ''}
    </span>
  )
}

export function Badge({ kind, children }: { kind: 'synthetic' | 'captured' | 'projected' | 'unavailable' | 'local'; children: ReactNode }) {
  return <span className={`badge badge--${kind}`}>{children}</span>
}
